flaskApp/grievances/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from flaskApp.models import Grievance





class PostGrievanceForm(FlaskForm):
    category_grievance = StringField('Grievance Category', validators=[DataRequired()])
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    grievance_picture = FileField('Uplaod Image', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Post')

flaskApp/grievances/routes.py
from flask import render_template, flash, redirect, url_for, request, abort, Blueprint
from flaskApp.models import Grievance
from flaskApp import bcrypt , db
from flaskApp.grievances.forms import PostGrievanceForm
from flaskApp.grievances.utils import save_grievance_picture
from flask_login import current_user, login_required


grievances = Blueprint('grievances', __name__)



@grievances.route("/grievance/new", methods=['GET', 'POST'])
@login_required
def new_grievance():
    form = PostGrievanceForm()
    if form.validate_on_submit():
        if form.grievance_picture.data:
            grievance_picture_file = save_grievance_picture(form.grievance_picture.data) 
            current_user.grievance_image_file = grievance_picture_file
        grievance = Grievance(category_grievance=form.category_grievance.data, title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(grievance)
        db.session.commit()
        flash('Your Grievance has been Sumbitted', 'success')
        grievance_image_file = url_for('static', filename='grievance_pic/' + current_user.grievance_image_file)
        return redirect(url_for('main.home'))
    return render_template('create_grievance.html', title='New Grievance', legend='New Grievance', form=form)


@grievances.route("/grievance/<int:grievance_id>")
def grievance(grievance_id):
    grievance = Grievance.query.get_or_404(grievance_id)
    return render_template('grievance.html', title=grievance.title, grievance=grievance)


@grievances.route("/grievance/<int:grievance_id>/update", methods=['GET', 'POST'])
def grievance_update(grievance_id):
    grievance = Grievance.query.get_or_404(grievance_id)
    if grievance.author != current_user:
        abort(403)
    form = PostGrievanceForm()
    if form.validate_on_submit():
        if form.grievance_picture.data:
            grievance_picture_file = save_grievance_picture(form.grievance_picture.data) 
            current_user.grievance_image_file = grievance_picture_file
        grievance.category_grievance = form.category_grievance.data
        grievance.title = form.title.data
        grievance.content = form.content.data
        db.session.commit()
        flash('Your Grievance has been updated!', 'success')
        grievance_image_file = url_for('static', filename='grievance_pic/' + current_user.grievance_image_file)
        return redirect(url_for('grievances.grievance', grievance_id=grievance.id))
    elif request.method == 'GET':
        form.category_grievance.data = grievance.category_grievance
        form.title.data = grievance.title
        form.content.data = grievance.content
    return render_template('create_grievance.html', title='Update Grievance', legend='Update Grievance', form=form)



@grievances.route("/grievance/<int:grievance_id>/delete", methods=['POST'])
def grievance_delete(grievance_id):
    grievance = Grievance.query.get_or_404(grievance_id)
    if grievance.author != current_user:
        abort(403)
    db.session.delete(grievance)
    db.session.commit()
    flash('Your Grievance has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskApp/main/routes.py
from flask import render_template, request, Blueprint
from flaskApp.models import User, Grievance


main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    grievances = Grievance.query.order_by(Grievance.date_posted.desc()).paginate(page=page, per_page=3)
    return render_template('home.html', grievances=grievances)

@main.route("/about")
def about():
    return render_template('about.html', title='About')

flaskApp/users/routes.py
from flask import render_template, flash, redirect, url_for, request, Blueprint
from flaskApp.models import User, Grievance
from flaskApp import bcrypt , db
from flaskApp.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flask_login import login_user, current_user, logout_user, login_required
from flaskApp.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created successfully!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
        
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful! Please check Username and Password.', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))



@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data) 
            current_user.image_file = picture_file 
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your accout has been Updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pic/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)




@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/user/<string:username>")
def user_grievances(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    grievances = Grievance.query.filter_by(author=user)\
        .order_by(Grievance.date_posted.desc())\
        .paginate(page=page, per_page=3)
    return render_template('user_grievances.html', grievances=grievances, user=user)

flaskApp/templates/about.html
{% extends "layout.html" %}

{% block content %}
<!-- <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
---- Include the above in your HEAD tag -------- -->

<!-- Services section -->
	<section id="what-we-do">
		<div class="container-fluid">
			<h2 class="section-title mb-2 h1">Sample About Page</h2>
			<p class="text-center text-muted h5">This is Sample About Page.</p>
			<div class="row mt-5">
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
					<div class="card">
						<div class="card-block block-1">
							<h3 class="card-title">About Us</h3>
							<p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
							<a href="#qb8D02" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
					<div class="card">
						<div class="card-block block-2">
							<h3 class="card-title">About Us</h3>
							<p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
							<a href="#qb8D02" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
					<div class="card">
						<div class="card-block block-3">
							<h3 class="card-title">About Us</h3>
							<p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
							<a href="#qb8D02" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
					<div class="card">
						<div class="card-block block-4">
							<h3 class="card-title">About Us</h3>
							<p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
							<a href="#qb8D02" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
					<div class="card">
						<div class="card-block block-5">
							<h3 class="card-title">About Us</h3>
							<p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
							<a href="#qb8D02" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
					<div class="card">
						<div class="card-block block-6">
							<h3 class="card-title">About Us</h3>
							<p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
							<a href="#qb8D02" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>	
	</section>
	<!-- /Services section -->
{%  endblock content%}

flaskApp/templates/account.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ image_file }}">
      <div class="media-body">
        <h2 class="account-heading">{{ current_user.username }}</h2>
        <p class="text-secondary">{{ current_user.email }}</p>
      </div>
    </div>
    <!-- FORM HERE -->
    <!-- <div class="content-section"> -->
      <form method="POST" action="" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Account Info</legend>
              <div class="form-group">
                  {{ form.username.label(class="form-control-label") }}
  
                  {% if form.username.errors %}
                      {{ form.username(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.username.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.username(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                  {{ form.email.label(class="form-control-label") }}
                  {% if form.email.errors %}
                      {{ form.email(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.email.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.email(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
              <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class="form-control-file") }}
                {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                        <span class="text-danger">{{ error }}</span></br>
                    {% endfor %}
                {% endif %}
            </div>
          </fieldset>
  
          <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
          
      </form>
  <!-- </div> -->
  </div>
{% endblock content %}

flaskApp/templates/create_grievance.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.category_grievance.label(class="form-control-label") }}

                {% if form.category_grievance.errors %}
                    {{ form.category_grievance(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.category_grievance(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}

                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}

                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.grievance_picture.label() }}
                {{ form.grievance_picture(class="form-control-file") }}
                {% if form.grievance_picture.errors %}
                    {% for error in form.grievance_picture.errors %}
                        <span class="text-danger">{{ error }}</span></br>
                    {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

flaskApp/templates/grievance.html
{% extends "layout.html" %}

{% block content %}

    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pic/' + grievance.author.image_file) }}">
        <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ grievance.author.username }}</a>
            <small class="text-muted">{{ grievance.date_posted.strftime('%d-%m-%Y') }}</small>
            {% if grievance.author == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('grievances.grievance_update', grievance_id=grievance.id) }}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
            {% endif %}
        </div>
        <h4>Title: {{ grievance.title }}</h4>
        <h5>Category: {{ grievance.category_grievance }}</h5>
        <p class="article-content">{{ grievance.content }}</p>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('grievances.grievance_delete', grievance_id=grievance.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
            </div>
        </div>
        </div>
    </div>
    
{% endblock content %}

flaskApp/templates/home.html
{% extends "layout.html" %}

{% block content %}

    {% for grievance in grievances.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pic/' + grievance.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_grievances', username=grievance.author.username) }}">{{ grievance.author.username }}</a>
              <small class="text-muted">{{ grievance.date_posted.strftime('%d-%m-%Y') }}</small>
            </div>
            <h4><a class="article-title" href="{{ url_for('grievances.grievance', grievance_id=grievance.id) }}">Title: {{ grievance.title }}</a></h4>
            <h5>Category: {{ grievance.category_grievance }}</h5>
            <p class="article-content">{{ grievance.content }}</p>
          </div>
        </article>
    {% endfor %}

    {% for page_num in grievances.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2, ) %}
      {% if page_num %}
        {% if grievances.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
    
{% endblock content %}

flaskApp/templates/layout.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% if title %}
        <title>Grievance Portal - {{ title }}</title>
    {% else %}
        <title>Grievance Portal</title>
    {% endif %}
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    
    <style>
        body {
        background-color: #ffffff;
        }
    </style>  
</head>
    
<body>

    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
              <a class="navbar-brand mr-4" href="/">Grievance Portal</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                  <a class="nav-item nav-link" href="/">Home</a>
                  <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                  {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="{{ url_for('grievances.new_grievance') }}">Post Grievance</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                  {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, messages in messages %}
                <div class="alert alert-{{ category }}">
                  {{ messages }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
        </div>
      </div>
      <div>
        {%block content%}{% endblock content %}
      </div>
    </main>
    
    
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
</body>
</html>                            

flaskApp/templates/login.html
{% extends "layout.html" %}

{% block content %}

  <!-- <div style="display: block; background-color: #ffffff;" class="box-login"> -->
    <div class="content-section">
        <form method="POST" action="">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
            <legend class="border-bottom mb-4">Login</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>

        <div class="form-check">
          {{ form.remember(class="form-check-input") }}
          {{ form.remember.label(class="form-check-label") }}
        </div>

        <div class="form-group pt-2">
            {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted ml-2">
              <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </small>
        </div>
        </form>
      </div>
      <div class="border-top pt-3">
        <small class="text-muted">
          Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
      </div>
    <!-- </div> -->

{% endblock content %}

flaskApp/templates/register.html
{% extends "layout.html" %}

{% block content %}

<!-- <div style="display: block; background-color: #ffffff;" class="box-register"> -->
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
        
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
    </small>
</div>
<!-- </div> -->

{% endblock content %}

flaskApp/templates/user_grievances.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ grievances.total }})</h1>
    {% for grievance in grievances.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pic/' + grievance.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_grievances', username=grievance.author.username) }}">{{ grievance.author.username }}</a>
              <small class="text-muted">{{ grievance.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('grievances.grievance', grievance_id=grievance.id) }}">{{ grievance.title }}</a></h2>
            <p class="article-content">{{ grievance.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in grievances.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if grievances.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_grievances', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_grievances', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}